# Generated by Django 5.2 on 2025-05-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_vector_extension'),
        ('users', '0002_user_phone_number'),
    ]

    operations = [
    ]
