# Generated by Django 5.2 on 2025-05-03 14:40

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20250503_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='embedding',
            field=pgvector.django.vector.VectorField(
                dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='platform',
            field=models.CharField(max_length=50),
        ),
    ]
