# Generated by Django 5.2 on 2025-05-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_embedding_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_currency',
            field=models.CharField(default='USD', help_text='Código ISO 4217 de la moneda por defecto', max_length=3),
        ),
    ]
