# Generated by Django 5.2 on 2025-05-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_telegramverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/Bogota', help_text='Zona horaria del usuario (ej: America/Bogota, America/New_York)', max_length=50),
        ),
    ]
