# Generated by Django 5.2 on 2025-05-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_email_user_is_active_user_is_verified_user_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_format',
        ),
        migrations.RemoveField(
            model_name='message',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='chat',
            name='platform',
            field=models.CharField(
                choices=[('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='UserPlatformIdentifier',
        ),
    ]
