# Generated by Django 5.2 on 2025-05-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_chat_is_active_remove_message_message_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Audio'), ('video', 'Video'), ('voice', 'Nota de voz'), ('document', 'Documento'), ('location', 'Ubicación'), ('contact', 'Contacto'), ('sticker', 'Sticker'), ('other', 'Otro')], default='text', help_text='Tipo de contenido del mensaje', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
