# Generated by Django 5.2 on 2025-05-09 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_message_content_type_message_media_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='message',
            name='metadata',
        ),
    ]
