# Generated by Django 5.2 on 2025-09-27 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_message_content_type_remove_message_media_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único del enlace (ej: empresa_abc_2024)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Campaña Empresa ABC)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del enlace o campaña')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si el enlace está activo para recibir nuevos usuarios')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del enlace (opcional)', null=True)),
                ('total_clicks', models.PositiveIntegerField(default=0, help_text='Total de clics registrados (si se implementa tracking de clics)')),
                ('total_registrations', models.PositiveIntegerField(default=0, help_text='Total de usuarios registrados desde este enlace')),
            ],
            options={
                'verbose_name': 'Enlace de Seguimiento',
                'verbose_name_plural': 'Enlaces de Seguimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='source_tracking_link',
            field=models.ForeignKey(blank=True, help_text='Enlace de seguimiento de origen del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.trackinglink'),
        ),
    ]
