# Generated by Django 5.2 on 2025-09-28 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_trackinglink_user_source_tracking_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Año del período de uso')),
                ('month', models.PositiveIntegerField(help_text='Mes del período de uso (1-12)')),
                ('expenses_count', models.PositiveIntegerField(default=0, help_text='Número de gastos registrados este mes')),
                ('incomes_count', models.PositiveIntegerField(default=0, help_text='Número de ingresos registrados este mes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usage', to='users.user')),
            ],
            options={
                'verbose_name': 'Uso Mensual',
                'verbose_name_plural': 'Uso Mensual',
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='users_month_user_id_2b94b6_idx'), models.Index(fields=['year', 'month'], name='users_month_year_740774_idx')],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
