# Generated by Django 5.2 on 2026-05-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='triggered_by',
            field=models.CharField(choices=[('initial', 'Initial'), ('chat_qa', 'Chat Q&A'), ('auto_inference', 'Auto inference'), ('context_drift', 'Context drift'), ('user_request', 'User request'), ('manual_override', 'Manual override')], max_length=24),
        ),
    ]
