# Generated by Django 5.2 on 2025-06-10 21:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#4CAF50', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_default', models.BooleanField(default=False, verbose_name='Categoría predefinida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Categoría de Ahorro',
                'verbose_name_plural': 'Categorías de Ahorro',
                'ordering': ['user', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la meta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto objetivo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto actual')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Fecha objetivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('completed', 'Completada'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('auto_save_enabled', models.BooleanField(default=False, verbose_name='Ahorro automático habilitado')),
                ('auto_save_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto de ahorro automático')),
                ('auto_save_frequency', models.CharField(blank=True, choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], max_length=20, null=True, verbose_name='Frecuencia de ahorro automático')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='savings.savingscategory', verbose_name='Categoría')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Meta de Ahorro',
                'verbose_name_plural': 'Metas de Ahorro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('transaction_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automático'), ('transfer', 'Transferencia'), ('withdrawal', 'Retiro'), ('interest', 'Interés'), ('bonus', 'Bono')], default='manual', max_length=20, verbose_name='Tipo de transacción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Origen del depósito')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('savings_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='savings.savingsgoal', verbose_name='Meta de ahorro')),
            ],
            options={
                'verbose_name': 'Depósito de Ahorro',
                'verbose_name_plural': 'Depósitos de Ahorro',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SavingsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la plantilla')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('suggested_amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto mínimo sugerido')),
                ('suggested_amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto máximo sugerido')),
                ('suggested_timeframe_months', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Plazo sugerido en meses')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridad sugerida')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='Consejos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.savingscategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Plantilla de Ahorro',
                'verbose_name_plural': 'Plantillas de Ahorro',
                'ordering': ['category', 'name'],
            },
        ),
    ]
