# Generated by Django 5.2 on 2025-05-03 14:51

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS vector;',
            reverse_sql='DROP EXTENSION IF EXISTS vector;'
        ),
        migrations.AddField(
            model_name='expense',
            name='category_str',
            field=models.CharField(blank=True, choices=[('Comida', 'Comida'), ('Transporte', 'Transporte'), ('Vivienda', 'Vivienda'), (
                'Entretenimiento', 'Entretenimiento'), ('Salud', 'Salud'), ('Educación', 'Educación'), ('Ropa', 'Ropa'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='embedding',
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='spent_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='raw_message',
            field=models.TextField(blank=True),
        ),
    ]
