# Generated by Django 5.2 on 2025-05-03 15:28

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_category_str_expense_embedding_expense_note_and_more'),
    ]

    operations = [
        VectorExtension(),
    ]
