# Generated by Django 5.2 on 2025-05-03 15:28

from django.db import migrations
from pgvector.django import HnswIndex


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_create_vector_extension'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=HnswIndex(
                name='expense_embedding_idx',
                fields=['embedding'],
                m=16,
                ef_construction=64,
                opclasses=['vector_cosine_ops'],
            ),
        ),
    ]
