# Generated by Django 5.2 on 2025-05-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_add_vector_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='expense_embedding_idx',
        ),
    ]
