# Generated by Django 5.2 on 2025-05-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_expense_expense_embedding_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
