# Generated by Django 5.2 on 2025-05-06 00:24

from django.db import migrations
from pgvector.django import HnswIndex


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_category_str'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=HnswIndex(
                name='expense_embedding_idx',
                fields=['embedding'],
                m=16,                     # Cantidad de conexiones por nodo
                ef_construction=64,       # Factor de exploración durante construcción
                # Operador de distancia coseno
                opclasses=['vector_cosine_ops'],
            ),
        ),
    ]
