# Generated by Django 5.2 on 2025-05-06 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_add_vector_index_v2'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='expense_embedding_idx',
        ),
    ]
