# Generated by Django 5.2 on 2025-05-06 00:33

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_populate_categories'),
        ('expenses', '0008_remove_expense_expense_embedding_idx'),
        ('users', '0008_telegramverification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='expense_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
