# Generated by Django 5.2 on 2025-06-21 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_migrate_user_categories_data'),
        ('expenses', '0009_expense_expense_embedding_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user_expense_category',
            field=models.ForeignKey(blank=True, help_text='Categoría de gasto personalizada por usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='categories.userexpensecategory'),
        ),
    ]
