# Generated by Django 5.2 on 2026-06-10 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_fix_null_user_expense_categories'),
        ('users', '0015_monthlyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to='users.message'),
        ),
    ]
