# Generated by Django 5.2 on 2026-03-12 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0012_fix_null_user_expense_categories'),
        ('users', '0015_monthlyusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.CharField(max_length=255)),
                ('access_token_encrypted', models.BinaryField()),
                ('refresh_token_encrypted', models.BinaryField()),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(default='https://www.googleapis.com/auth/gmail.readonly')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_account', to='users.user')),
            ],
            options={
                'verbose_name': 'Cuenta de Google',
                'verbose_name_plural': 'Cuentas de Google',
            },
        ),
        migrations.CreateModel(
            name='GmailWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.CharField(blank=True, max_length=255, null=True)),
                ('watch_expiration', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch', to='gmailbot.googleaccount')),
            ],
            options={
                'verbose_name': 'Gmail Watch',
                'verbose_name_plural': 'Gmail Watches',
            },
        ),
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=255)),
                ('subject', models.CharField(default='', max_length=500)),
                ('sender', models.CharField(default='', max_length=255)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('is_purchase', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'Pendiente'), ('processed', 'Procesado'), ('skipped', 'Omitido'), ('error', 'Error')], default='pending', max_length=20)),
                ('ai_response', models.TextField(blank=True, default='')),
                ('awaiting_categorization', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_emails', to='expenses.expense')),
                ('google_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_emails', to='gmailbot.googleaccount')),
            ],
            options={
                'verbose_name': 'Email Procesado',
                'verbose_name_plural': 'Emails Procesados',
                'ordering': ['-created_at'],
                'unique_together': {('google_account', 'gmail_message_id')},
            },
        ),
    ]
