# Generated by Django 5.2 on 2026-05-26 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailbot', '0005_drop_legacy_google_models'),
        ('users', '0015_monthlyusage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='composioconnection',
            name='gmailbot_compconn_pending_idx',
        ),
        migrations.AlterField(
            model_name='composioconnection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='composioconnection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='composio_connection', to='users.user'),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_emails', to='users.user'),
        ),
    ]
