# Generated by Django 5.2 on 2026-06-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailbot', '0006_remove_composioconnection_gmailbot_compconn_pending_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedemail',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processed', 'Procesado'), ('skipped', 'Omitido'), ('duplicate', 'Duplicado de otra transacción'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
