# Generated by Django 5.2 on 2025-05-03 14:40

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
        ('users', '0004_user_embedding_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='user',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='message_type',
            field=models.CharField(
                choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('category', models.CharField(choices=[('Comida', 'Comida'), ('Transporte', 'Transporte'), ('Vivienda', 'Vivienda'), (
                    'Entretenimiento', 'Entretenimiento'), ('Salud', 'Salud'), ('Educación', 'Educación'), ('Ropa', 'Ropa'), ('Otros', 'Otros')], max_length=20)),
                ('spent_at', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(
                    dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='telegram_expenses', to='users.user')),
            ],
        ),
    ]
