# Generated by Django 5.2 on 2025-05-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_alter_telegramchat_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
