# Generated by Django 5.2 on 2025-05-03 16:03

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_delete_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
