# Generated by Django 5.2 on 2025-05-09 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0004_telegrammessage_embedding'),
        ('users', '0010_user_email_user_is_active_user_is_verified_user_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('verification_code', models.CharField(max_length=6)),
                ('whatsapp_chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('used_for_registration', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='telegramchat',
            old_name='chat_id',
            new_name='telegram_chat_id',
        ),
        migrations.RenameField(
            model_name='telegrammessage',
            old_name='message_id',
            new_name='telegram_message_id',
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='generic_chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_chat', to='users.chat'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='generic_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_message', to='users.message'),
        ),
    ]
