# Generated by Django 5.2 on 2025-05-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0005_whatsappverification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsAppVerification',
        ),
        migrations.RenameField(
            model_name='telegramchat',
            old_name='telegram_chat_id',
            new_name='chat_id',
        ),
        migrations.RenameField(
            model_name='telegrammessage',
            old_name='telegram_message_id',
            new_name='message_id',
        ),
        migrations.RemoveField(
            model_name='telegramchat',
            name='generic_chat',
        ),
        migrations.RemoveField(
            model_name='telegrammessage',
            name='generic_message',
        ),
    ]
