# Generated by Django 5.2 on 2025-05-05 21:50

from django.db import migrations


def create_predefined_categories(apps, schema_editor):
    """
    Crea las categorías predefinidas en la base de datos.
    """
    Category = apps.get_model('categories', 'Category')

    # Obtenemos las categorías predefinidas de la clase Category
    from categories.models import Category as CategoryModel
    predefined_categories = CategoryModel.PREDEFINED_CATEGORIES

    # Creamos las categorías que no existan ya
    for category_name in predefined_categories:
        Category.objects.get_or_create(name=category_name)


def reverse_migration(apps, schema_editor):
    """
    No eliminamos las categorías en caso de rollback para no afectar
    a los gastos que ya estén utilizando estas categorías.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_predefined_categories, reverse_migration),
    ]
