# Generated by Django 5.2 on 2025-05-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_populate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#CCCCCC', max_length=7),
        ),
    ]
