# Generated by Django 5.2 on 2025-05-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_assign_category_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='examples',
            field=models.TextField(blank=True, null=True),
        ),
    ]
