# Generated by Django 5.2 on 2025-05-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#CCCCCC', max_length=7)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
