# Generated by Django 5.2 on 2025-05-08 01:40

import django.db.models.deletion
from django.db import migrations, models


def set_categories_to_null(apps, schema_editor):
    """
    Establece todas las categorías a NULL para evitar problemas de integridad referencial
    """
    Income = apps.get_model('income', 'Income')
    # Guardar category_str si no existe
    for income in Income.objects.filter(category__isnull=False):
        if not income.category_str:
            income.category_str = income.category.name
            income.save()
    # Establecer todas las categorías a NULL
    Income.objects.all().update(category=None)


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_create_income_category'),
    ]

    operations = [
        # Primero establecer todas las categorías a NULL
        migrations.RunPython(set_categories_to_null),

        # Luego cambiar la relación
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='income.incomecategory'),
        ),
    ]
