# Generated by Django 5.2 on 2025-05-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_update_income_category_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
    ]
