# Generated by Django 5.2 on 2025-05-10 02:52

from django.db import migrations


def populate_income_categories(apps, schema_editor):
    """
    Función para poblar las categorías de ingresos predefinidas con sus descripciones,
    ejemplos y colores
    """
    # Obtenemos el modelo IncomeCategory del estado de las aplicaciones
    IncomeCategory = apps.get_model('income', 'IncomeCategory')

    # Categorías predefinidas
    categories_data = [
        {
            "name": "Salario o Trabajo Fijo",
            "description": "Ingresos provenientes de empleos formales o contratos fijos.",
            "example": "Nómina, contratos laborales, trabajo a tiempo completo",
            "color": "#1E40AF"
        },
        {
            "name": "Trabajo Independiente o Freelance",
            "description": "Ingresos por trabajos por cuenta propia o por proyectos.",
            "example": "Servicios profesionales, diseño, asesorías, honorarios",
            "color": "#3B82F6"
        },
        {
            "name": "Negocios o Emprendimientos",
            "description": "Ingresos generados por negocios propios.",
            "example": "Ventas, e-commerce, microempresa",
            "color": "#0F766E"
        },
        {
            "name": "Inversiones",
            "description": "Rendimientos obtenidos por instrumentos financieros.",
            "example": "Dividendos, acciones, cripto, rendimientos bancarios",
            "color": "#10B981"
        },
        {
            "name": "Alquileres y Activos",
            "description": "Ingresos pasivos generados por propiedades o activos.",
            "example": "Arriendos, leasing, renting",
            "color": "#78350F"
        },
        {
            "name": "Regalías y Derechos",
            "description": "Ingresos por propiedad intelectual o contenido.",
            "example": "Regalías por música, libros, patentes",
            "color": "#8B5CF6"
        },
        {
            "name": "Apoyos o Subsidios",
            "description": "Ingresos no laborales provenientes de ayudas externas.",
            "example": "Subsidios estatales, becas, ayudas familiares",
            "color": "#F59E0B"
        },
        {
            "name": "Premios y Sorteos",
            "description": "Ingresos ocasionales por suerte o concursos.",
            "example": "Loterías, rifas, juegos de azar",
            "color": "#DC2626"
        },
        {
            "name": "Venta de Bienes",
            "description": "Ingresos por venta de objetos personales o activos.",
            "example": "Venta de carro, muebles, tecnología",
            "color": "#A16207"
        }
    ]

    # Creamos o actualizamos las categorías
    for category_data in categories_data:
        IncomeCategory.objects.update_or_create(
            name=category_data["name"],
            defaults={
                "description": category_data["description"],
                "example": category_data["example"],
                "color": category_data["color"]
            }
        )


def reverse_populate_income_categories(apps, schema_editor):
    """
    Función para revertir la población de categorías (opcional)
    """
    # No eliminamos las categorías en la reversión para evitar problemas con datos existentes
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_incomecategory_description_incomecategory_example'),
    ]

    operations = [
        migrations.RunPython(
            populate_income_categories,
            reverse_populate_income_categories
        ),
    ]
