# Generated by Django 5.2 on 2025-06-21 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_migrate_user_categories_data'),
        ('income', '0005_populate_income_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='user_income_category',
            field=models.ForeignKey(blank=True, help_text='Categoría de ingreso personalizada por usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='categories.userincomecategory'),
        ),
    ]
