"""
Django settings for cashbotapp project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url
import logging
# Cargar variables de entorno desde .env
load_dotenv()

# Configurar logging
logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


DATABASE_URL = os.getenv("DATABASE_URL")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tu+u#i1h(6eq-m5l638yf-2as0w@wvu)4+m-ug364dno^s(bn3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'pgvector.django',
    'drf_spectacular',
    'users',
    'expenses',
    'categories',
    'telegrambot',
    'corsheaders',
    'income',
    'whatsappbot',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'cashbotapp.auth.CustomJWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'cashbotapp.utils.custom_exception_handler',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'cashbotapp.middleware.DatabaseConnectionMiddleware',
    'cashbotapp.middleware.AuthLoggingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cashbotapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cashbotapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Configuración de Supabase
DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv(
            "DATABASE_URL", DATABASE_URL),
        conn_max_age=60,  # Mantener conexiones vivas por 60 segundos
        ssl_require=not DEBUG,  # SSL requerido solo en producción
        conn_health_checks=True,
    )
}

DATABASES["default"]["ENGINE"] = "django.db.backends.postgresql"


# Configuración normal de PostgreSQL
# En desarrollo preferimos SSL, en producción lo requerimos
ssl_mode = 'prefer' if DEBUG else 'require'
logger.info(f"Modo SSL configurado como: {ssl_mode} (DEBUG={DEBUG})")

DATABASES['default']['OPTIONS'] = {
    'application_name': 'cashbot',
    'connect_timeout': 30,
    'keepalives': 1,
    'keepalives_idle': 30,
    'keepalives_interval': 10,
    'keepalives_count': 5,
    'sslmode': ssl_mode,
}

# Imprimir configuración de la conexión
print("="*50)
print("CONFIGURACIÓN DE CONEXIÓN A LA BASE DE DATOS SUPABASE:")
print(f"Connection max age: {DATABASES['default']['CONN_MAX_AGE']} segundos")
print(
    f"SSL: {DATABASES['default']['OPTIONS'].get('sslmode', 'No configurado')}")
print(
    f"Keepalives: {DATABASES['default']['OPTIONS'].get('keepalives', 'No configurado')}")
print("="*50)

# Configuración de API de Supabase
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Telegram Bot
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_WEBHOOK_URL = os.getenv('TELEGRAM_WEBHOOK_URL', '')

# Configuración de OpenAI
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# Configuración de WhatsApp Bot (Evolution API)
EVOLUTION_API_URL = os.getenv('EVOLUTION_API_URL', '')
EVOLUTION_API_KEY = os.getenv('EVOLUTION_API_KEY', '')
GLOBAL_API_KEY = os.getenv('AUTHENTICATION_API_KEY', '')
# Nombre de la instancia predeterminada
WHATSAPP_DEFAULT_INSTANCE = os.getenv(
    'WHATSAPP_DEFAULT_INSTANCE', 'Tresqu Test')
WHATSAPP_DEFAULT_EVENTS = [
    "QRCODE_UPDATED",
    "MESSAGES_UPSERT",
    "MESSAGES_UPDATE",
    "CONNECTION_UPDATE",
    "SEND_MESSAGE",
]

SPECTACULAR_SETTINGS = {
    'TITLE': 'Cashbot API',
    'DESCRIPTION': 'API para la gestión de Cashbot',
    'VERSION': '0.0.1',
    'SERVE_INCLUDE_SCHEMA': True,
    'SCHEMA_PATH_PREFIX': None,
}

# Para permitir que el widget de Telegram funcione correctamente
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

# Configuración de JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    # Deshabilitar la regla de autenticación de usuario por defecto
    'USER_AUTHENTICATION_RULE': 'cashbotapp.auth.custom_user_authentication_rule',
}

# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'cashbotapp': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'expenses': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'users': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'whatsappbot': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Configuración de CORS
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Configuración de administradores de Telegram
# Los IDs de usuario de Telegram que pueden enviar mensajes masivos
TELEGRAM_ADMIN_IDS = [
    7519177293,  # Reemplaza esto con tu ID de usuario de Telegram
]
