# Generated by Django 5.2 on 2026-05-23 18:13

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0001_initial'),
        ('users', '0015_monthlyusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_trade_usd', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('max_daily_move_usd', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('allowed_symbols', models.JSONField(default=list)),
                ('blocked_symbols', models.JSONField(default=list)),
                ('require_2step_above_usd', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_limits', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='statements/')),
                ('source_type', models.CharField(choices=[('bank', 'Bank'), ('card', 'Card')], max_length=16)),
                ('bank_name', models.CharField(blank=True, max_length=64)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('parsing', 'Parsing'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=16)),
                ('txs_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_statements', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='WallbitAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_api_key', models.TextField()),
                ('scope_hint', models.CharField(default='read,trade', max_length=32)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('revoked', 'Revoked'), ('error', 'Error')], default='connected', max_length=16)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('kill_switch_until', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallbit_account', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='WallbitChestLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallbit_chest_id', models.IntegerField()),
                ('auto_top_up_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auto_top_up_cron', models.CharField(blank=True, max_length=64)),
                ('savings_goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallbit_chest', to='savings.savingsgoal')),
            ],
        ),
        migrations.CreateModel(
            name='WallbitTxMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallbit_uuid', models.CharField(max_length=64, unique=True)),
                ('tx_type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('source_currency', models.CharField(max_length=8)),
                ('dest_currency', models.CharField(max_length=8)),
                ('source_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('dest_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('external_address', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at_wallbit', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
                ('raw', models.JSONField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txs', to='wallbit.wallbitaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('STOCK', 'Stock'), ('ETF', 'ETF'), ('BOND', 'Bond'), ('ROBO', 'Robo-advisor'), ('CHEST', 'Chest')], max_length=8)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], max_length=8)),
                ('symbol', models.CharField(blank=True, max_length=16)),
                ('chest_category', models.CharField(blank=True, max_length=32)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('shares', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='users.user')),
                ('wallbit_tx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment', to='wallbit.wallbittxmirror')),
            ],
        ),
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('web', 'Web'), ('voice', 'Voice')], max_length=16)),
                ('user_message', models.TextField()),
                ('agent_reasoning', models.TextField(blank=True)),
                ('tools_called', models.JSONField(default=list)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('executed', models.BooleanField(default=False)),
                ('wallbit_tx_uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_decisions', to='users.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='wallbit_age_user_id_0407a3_idx'), models.Index(fields=['requires_confirmation', 'executed'], name='wallbit_age_require_504a1c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wallbittxmirror',
            index=models.Index(fields=['account', '-created_at_wallbit'], name='wallbit_wal_account_cdc25e_idx'),
        ),
        migrations.AddIndex(
            model_name='wallbittxmirror',
            index=models.Index(fields=['tx_type'], name='wallbit_wal_tx_type_75205a_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', '-created_at'], name='wallbit_inv_user_id_24ccae_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['kind', 'action'], name='wallbit_inv_kind_7f46f3_idx'),
        ),
    ]
