# Generated by Django 5.2 on 2026-05-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallbit', '0002_investment_executed_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='investment',
            new_name='wallbit_inv_user_id_42e5ea_idx',
            old_name='wallbit_inv_user_exec_idx',
        ),
    ]
